<?php

return [
    'Mood Stabilizers' => [
        "Depakote (Valproic Acid)",
        "Lamictal (Lamotrigine)",
        "Lithium Carbonate",
        "Tegretol (Carbamazepine)",
        "Trileptal (Oxcarbazepine)",
    ],
    'Anti-Psychotics' => [
        "Abilify (Aripiprazole)",
        "Clozaril (Clozapine)",
        "Geodon (Ziprasidone)",
        "Latuda (Lurasidone)",
        "Risperdal (Risperidone)",
        "Seroquel (Quetiapine)",
        "Stelazine (Trifluoperazine)",
        "Vraylar (Cariprazine)",
        "Zyprexa (Olanzapine)",
    ],
    'Stimulant & Non-Stimulant ADHD Meds' => [
        "Adderall (Amphetamine/dextroamphetamine)",
        "Concerta (Methylphenidate)",
        "Dexedrine (amphetamine)",
        "Focalin XR (dexmethylphenidate)",
        "Intuniv (Guanfacine)",
        "Qelbree (Viloxazine)",
        "Quillivant XR (methylphenidate)",
        "Ritalin (Methylphenidate)",
        "Strattera (Atomoxetine Hydrochloride)",
        "Vyvanse (Lisdexamfetamine)",
    ],
    'Antidepressants & Anti-Anxiety Medications' => [
        "Ativan (Lorazepam)",
        "Celexa (Citalopram - SSRI)",
        "Cymbalta (Duloxetine - SNRI)",
        "Effexor (Venlafaxine - SNRI)",
        "Klonopin (Clonazepam)",
        "Lexapro (Escitalopram - SSRI)",
        "Luvox (Fluvoxamine - SSRI)",
        "Paxil (Paroxetine - SSRI)",
        "Pristiq (Desvenlafaxine  - SNRI)",
        "Prozac (Fluoxetine - SSRI)",
        "Remeron (Mirtazapine - Atypical)",
        "Trazodone (Atypical)",
        "Valium (Diazepam)",
        "Viibryd (Vilazodone - Atypical)",
        "Wellbutrin (Bupropion  - Atypical)",
        "Xanax (Alprazolam)",
        "Zoloft (Sertraline - SSRI)",
    ],
    'Other Common Prescriptions' => [
        "Bentyl (Dicyclomine)",
        "Clonidine",
        "Cogentin (Benztropine)",
        "Divalproex (Sodium Valproate)",
        "Gabapentin",
        "Glucophage (Metformin)",
        "Hydroxyzine",
        "Inderal (Propranolol)",
        "Ketamine",
        "Lipitor (Atorvastatin)",
        "Minipress (Prazosin)",
        "Synthroid (Levothyroxine)",
    ],
    'Over the Counter / Supplements' => [
        "Benadryl",
        "Claritin",
        "Melatonin",
        "Methylfolate",
        "N-Acetyl Cysteine",
        "Vitamin D",
    ],
    'Other' => [
        'Other' => 'Other / Not Listed'
    ]
];